FROM golang:1.21-alpine AS builder
WORKDIR /app
RUN apk add --no-cache git ca-certificates tzdata
COPY go.mod ./
ENV GOPROXY=https://goproxy.cn,direct
ENV GOSUMDB=off
RUN go mod tidy && go mod download
COPY . .
RUN go mod tidy && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o migrate cmd/migrate/main.go

FROM alpine:3.18
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /root/
COPY --from=builder /app/migrate .
COPY --from=builder /app/configs ./configs
CMD ["./migrate"]